version: "3.8"

services:
  storage:
    image: minio/minio
    restart: always
    environment:
      MINIO_ROOT_USER: 'minio_admin'
      MINIO_ROOT_PASSWORD: 'minio_admin'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    volumes:
      - storage:/var/lib/minio/data
    ports:
      - "9010:9000"
      - "9011:9001"
    command: server /data
    networks:
      - helios-net

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: helios_admin
      POSTGRES_PASSWORD: dummy
      POSTGRES_DB: helios
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "55432:5432"
    logging:
      driver: none
    networks:
      - helios-net

  api:
    build:
      context: https://github.com/helios-strategia/helios-api.git
      dockerfile: Dockerfile
    depends_on:
      - db
      - storage
    ports:
      - "3034:3034"
    environment:
      NODE_CONFIG: '{ "database": { "host": "db", "port": 5432 }, "file_storage": { "minio": { "end_point": "storage", "port": 9000 } } }'
    networks:
      - helios-net

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    networks:
      - helios-net
    ports:
      - 3300:80
    depends_on:
      - api

networks:
  helios-net:
    driver: bridge

volumes:
  db_data:
  storage:
